### ISSUE TITLE
Problem with running influxdb-cli

### ISSUE THREAD

**Issue by allertec** [FGRibreau/influxdb-cli#16]
Hi,

I think I found a problem in your documentation. It shouldn`t be run as per blow:
nodejs ./influxdb-cli

At least this works on my Ubuntu 14.04LTS. Just "node" won`t work.

Thank you

**Comment by FGRibreau** [comment]
Hello,

This is not related with influxdb-cli, you may have forgotten to install it using `npm -g`. 
If you did, then it's an issue with your npm installation (installed global packages are not available in `$PATH`).
I recommend [nvm](https://github.com/creationix/nvm) for managing nodejs versions.
