### ISSUE TITLE
received this error when installing cli

### ISSUE THREAD

**Issue by densone** [FGRibreau/influxdb-cli#6]
root@john:~#  npm install influxdb-cli -g
npm http GET https://registry.npmjs.org/influxdb-cli
npm http 200 https://registry.npmjs.org/influxdb-cli
npm http GET https://registry.npmjs.org/influxdb-cli/-/influxdb-cli-0.1.0.tgz
npm http 200 https://registry.npmjs.org/influxdb-cli/-/influxdb-cli-0.1.0.tgz
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/request
npm ERR! git clone https://github.com/FGRibreau/cli-table.git execvp(): No such file or directory
npm ERR! error installing influxdb-cli@0.1.0

npm ERR! Error: `git "clone" "https://github.com/FGRibreau/cli-table.git" "/tmp/npm-1384839346118/1384839346515-0.6295274342410266"` failed with 127
npm ERR!     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/exec.js:49:20)
npm ERR!     at ChildProcess.emit (events.js:70:17)
npm ERR!     at maybeExit (child_process.js:360:16)
npm ERR!     at Socket.<anonymous> (child_process.js:465:7)
npm ERR!     at Socket.emit (events.js:67:17)
npm ERR!     at Array.0 (net.js:320:10)
npm ERR!     at EventEmitter._tickCallback (node.js:192:41)
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /root/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.5.0-41-generic
npm ERR! command "node" "/usr/bin/npm" "install" "influxdb-cli" "-g"
npm ERR! cwd /root
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message `git "clone" "https://github.com/FGRibreau/cli-table.git" "/tmp/npm-1384839346118/1384839346515-0.6295274342410266"` failed with 127
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm not ok
root@john:~#

**Comment by densone** [comment]
haha, nevermind. git was not installed on the server.

**Comment by FGRibreau** [comment]
:)
